name: Sync gocn

on:
  workflow_dispatch:
  schedule:
    - cron: "17 18 * * *"

jobs:
  run_program:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v4.0.1
        with:
          go-version: 1.19.x
    
      - name: Restore Go Module Cache
        uses: actions/cache@v2
        with:
          path: ~/go/internal/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build and Run program
        run: |
          go run ./...
