name: Sync gocn

on:
  workflow_dispatch:
  schedule:
    - cron: "17 18 * * *"

jobs:
  run_program:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v4.0.1
        with:
          go-version: 1.18.x

      - name: Build and Run program
        run: |
          go mod tidy
          cd /gocn
          go run main.go
