name: Sync gocn

on:
  schedule:
    - cron: "17 18 * * *"

jobs:
  run_program:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v4.0.1
        with:
          go-version: 1.20

      - name: Download dependencies
        run: go mod download

      - name: Build and Run program
        run: |
          go build main.go
          ./main
