name: Sync gocn

on:
  workflow_dispatch:
  schedule:
    - cron: "17 18 * * *"

jobs:
  run_program:
    runs-on: ubuntu-latest
    steps:    
      - name: Add private key to SSH agent
        run: |
          ssh-add <(echo "${{ secrets.PRIVATE_SSH_KEY }}")
          
      - name: Set SSH_AUTH_SOCK environment variable
        run: |
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v4.0.1
        with:
          go-version: 1.19.x

      - name: Build and Run program
        run: |
          go mod tidy
          go run ./...
        env:
          SSH_AUTH_SOCK: $SSH_AUTH_SOCK
